### PR TITLE
Retry `cf api` to avoid flakes

### PR DESCRIPTION
**Pull request by georgethebeatle**
Adding retry to `cf api` request to mitigate flakes in garden pipelines.

More details in: https://www.pivotaltracker.com/story/show/129349109

[#129349109]

Signed-off-by: Petar Petrov <pppepito86@gmail.com>

### CODE REVIEW

**Comment by ematpl** [comment]
Thanks, @georgethebeatle. Could you explain more about the flakes that you see in the Garden CI jobs? @jfmyers9 and others may be able to comment further, but I don't think the Diego team encounters those at all on in its pipeline.

Best,
Eric

**Comment by georgethebeatle** [comment]
In our cf-deploy jobs in CI we have a task that enables docker immediately after deployment finishes: https://github.com/cloudfoundry/garden-ci/blob/master/ci/pipelines/main.yml#L337

It turns out that sometimes cf api needs some time to become accessible after bosh completes. So for both garden-linux and garden-runc we are experiencing flakes like this one: https://garden.ci.cf-app.com/pipelines/main/jobs/fangorn-cf-deploy/builds/83

That's basically all there is to say...

**Comment by ematpl** [comment]
Right, the Diego pipeline behaves similarly (see https://diego.ci.cf-app.com/teams/main/pipelines/main/jobs/ketchup-cf-deploy/builds/1242, for example), but we don't observe this problem for our deployments, which are multi-AZ. My understanding is that fangorn has only 1 AZ, though, so do those failures arise because the single gorouter has just updated but is not registered as healthy with its ELB yet? If that's the case, is there a different strategy that would work to ensure the gorouter is healthy before proceeding with these `cf` commands?

Also, have you tried setting a number of retry attempts on that step (http://concourse.ci/retry-step.html)?

Thanks,
Eric

**Comment by georgethebeatle** [comment]
Thanks @ematpl 
We we will consider these suggestions!

**Comment by georgethebeatle** [comment]
Thank you @ematpl we decided to use the `attempts` feature of concourse! Closing.

**Comment by ematpl** [comment]
Thanks, @georgethebeatle!

**Pull request closed without merging**
